export const STOCKS = [
  {t:"NVDA",n:"Nvidia",s:"Halvledere",d:"nvidia.com",c:0.35},
  {t:"AMD",n:"Advanced Micro Devices",s:"Halvledere",d:"amd.com",c:-4.0},
  {t:"TSM",n:"Taiwan Semiconductor",s:"Halvledere",d:"tsmc.com",c:-2.3},
  {t:"AVGO",n:"Broadcom",s:"Halvledere",d:"broadcom.com",c:0.55},
  {t:"QCOM",n:"Qualcomm",s:"Halvledere",d:"qualcomm.com",c:0.7},
  {t:"INTC",n:"Intel",s:"Halvledere",d:"intel.com",c:0.6},
  {t:"MU",n:"Micron",s:"Halvledere",d:"micron.com",c:3.6},
  {t:"ASML",n:"ASML",s:"Halvledere",d:"asml.com",c:0.55},
  {t:"ARM",n:"Arm Holdings",s:"Halvledere",d:"arm.com",c:-3.3},
  {t:"TXN",n:"Texas Instruments",s:"Halvledere",d:"ti.com",c:-2.0},
  {t:"ADI",n:"Analog Devices",s:"Halvledere",d:"analog.com",c:-4.2},
  {t:"NXPI",n:"NXP Semiconductors",s:"Halvledere",d:"nxp.com",c:1.45},
  {t:"AAPL",n:"Apple",s:"Software",d:"apple.com",c:-0.2},
  {t:"MSFT",n:"Microsoft",s:"Software",d:"microsoft.com",c:1.2},
  {t:"ORCL",n:"Oracle",s:"Software",d:"oracle.com",c:0.7},
  {t:"CRM",n:"Salesforce",s:"Software",d:"salesforce.com",c:-3.2},
  {t:"ADBE",n:"Adobe",s:"Software",d:"adobe.com",c:-1.1},
  {t:"PLTR",n:"Palantir",s:"Software",d:"palantir.com",c:1.6},
  {t:"NOW",n:"ServiceNow",s:"Software",d:"servicenow.com",c:-2.3},
  {t:"SNOW",n:"Snowflake",s:"Software",d:"snowflake.com",c:1.85},
  {t:"CRWD",n:"CrowdStrike",s:"Software",d:"crowdstrike.com",c:0.7},
  {t:"PANW",n:"Palo Alto Networks",s:"Software",d:"paloaltonetworks.com",c:1.0},
  {t:"GOOGL",n:"Alphabet",s:"Internet",d:"google.com",c:4.3},
  {t:"META",n:"Meta Platforms",s:"Internet",d:"meta.com",c:0.25},
  {t:"AMZN",n:"Amazon",s:"Internet",d:"amazon.com",c:1.0},
  {t:"NFLX",n:"Netflix",s:"Internet",d:"netflix.com",c:1.1},
  {t:"UBER",n:"Uber",s:"Internet",d:"uber.com",c:0.6},
  {t:"ABNB",n:"Airbnb",s:"Internet",d:"airbnb.com",c:-0.75},
  {t:"SHOP",n:"Shopify",s:"Internet",d:"shopify.com",c:1.2},
  {t:"SPOT",n:"Spotify",s:"Internet",d:"spotify.com",c:1.8},
  {t:"TSLA",n:"Tesla",s:"Bil",d:"tesla.com",c:0.9},
  {t:"TM",n:"Toyota",s:"Bil",d:"toyota.com",c:3.55},
  {t:"F",n:"Ford",s:"Bil",d:"ford.com",c:-1.0},
  {t:"GM",n:"General Motors",s:"Bil",d:"gm.com",c:2.9},
  {t:"RIVN",n:"Rivian",s:"Bil",d:"rivian.com",c:1.45},
  {t:"LCID",n:"Lucid",s:"Bil",d:"lucidmotors.com",c:-0.3},
  {t:"STLA",n:"Stellantis",s:"Bil",d:"stellantis.com",c:0.9},
  {t:"NIO",n:"NIO",s:"Bil",d:"nio.com",c:-3.0},
  {t:"LI",n:"Li Auto",s:"Bil",d:"lixiang.com",c:2.95},
  {t:"XPEV",n:"XPeng",s:"Bil",d:"xiaopeng.com",c:1.65},
  {t:"TMUS",n:"T-Mobile US",s:"Telekom",d:"t-mobile.com",c:1.95},
  {t:"VZ",n:"Verizon",s:"Telekom",d:"verizon.com",c:4.3},
  {t:"T",n:"AT&T",s:"Telekom",d:"att.com",c:-0.3},
  {t:"CMCSA",n:"Comcast",s:"Telekom",d:"comcast.com",c:3.45},
  {t:"CHTR",n:"Charter",s:"Telekom",d:"charter.com",c:0.75},
  {t:"NVO",n:"Novo Nordisk",s:"Pharma",d:"novonordisk.com",c:-2.35},
  {t:"LLY",n:"Eli Lilly",s:"Pharma",d:"lilly.com",c:-2.45},
  {t:"PFE",n:"Pfizer",s:"Pharma",d:"pfizer.com",c:-3.55},
  {t:"JNJ",n:"Johnson & Johnson",s:"Pharma",d:"jnj.com",c:-3.2},
  {t:"MRK",n:"Merck",s:"Pharma",d:"merck.com",c:-2.8},
  {t:"ABBV",n:"AbbVie",s:"Pharma",d:"abbvie.com",c:-0.35},
  {t:"AZN",n:"AstraZeneca",s:"Pharma",d:"astrazeneca.com",c:-2.85},
  {t:"NVS",n:"Novartis",s:"Pharma",d:"novartis.com",c:-2.15},
  {t:"GSK",n:"GSK",s:"Pharma",d:"gsk.com",c:-3.05},
  {t:"BMY",n:"Bristol Myers Squibb",s:"Pharma",d:"bms.com",c:-2.9},
  {t:"BNTX",n:"BioNTech",s:"Biotek",d:"biontech.com",c:1.3},
  {t:"MRNA",n:"Moderna",s:"Biotek",d:"modernatx.com",c:0.6},
  {t:"VRTX",n:"Vertex",s:"Biotek",d:"vrtx.com",c:2.5},
  {t:"REGN",n:"Regeneron",s:"Biotek",d:"regeneron.com",c:0.5},
  {t:"VERU",n:"Veru",s:"Biotek",d:"verupharma.com",c:1.6},
  {t:"CRSP",n:"CRISPR Therapeutics",s:"Biotek",d:"crisprtx.com",c:1.1},
  {t:"BIIB",n:"Biogen",s:"Biotek",d:"biogen.com",c:-0.6},
  {t:"ILMN",n:"Illumina",s:"Biotek",d:"illumina.com",c:0.7},
  {t:"FRD",n:"Friedman Industries",s:"Materialer",d:"friedmanindustries.com",c:-3.5},
  {t:"NUE",n:"Nucor",s:"Materialer",d:"nucor.com",c:-2.9},
  {t:"STLD",n:"Steel Dynamics",s:"Materialer",d:"steeldynamics.com",c:1.05},
  {t:"CLF",n:"Cleveland-Cliffs",s:"Materialer",d:"clevelandcliffs.com",c:-3.85},
  {t:"RIO",n:"Rio Tinto",s:"Materialer",d:"riotinto.com",c:-2.8},
  {t:"BHP",n:"BHP Group",s:"Materialer",d:"bhp.com",c:-3.6},
  {t:"FCX",n:"Freeport-McMoRan",s:"Materialer",d:"fcx.com",c:-3.25},
  {t:"ALB",n:"Albemarle",s:"Materialer",d:"albemarle.com",c:-4.15},
  {t:"LMT",n:"Lockheed Martin",s:"Forsvar",d:"lockheedmartin.com",c:-2.65},
  {t:"RTX",n:"RTX Corp",s:"Forsvar",d:"rtx.com",c:-1.8},
  {t:"NOC",n:"Northrop Grumman",s:"Forsvar",d:"northropgrumman.com",c:-3.3},
  {t:"GD",n:"General Dynamics",s:"Forsvar",d:"gd.com",c:2.45},
  {t:"BA",n:"Boeing",s:"Forsvar",d:"boeing.com",c:2.05},
  {t:"LHX",n:"L3Harris",s:"Forsvar",d:"l3harris.com",c:-2.7},
  {t:"ONDS",n:"Ondas Holdings",s:"Forsvar",d:"ondas.com",c:0.9},
  {t:"SPCX",n:"SpaceX",s:"Rumfart",d:"spacex.com",c:1.4},
  {t:"RKLB",n:"Rocket Lab",s:"Rumfart",d:"rocketlabusa.com",c:0.45},
  {t:"FLY",n:"Firefly Aerospace",s:"Rumfart",d:"fireflyspace.com",c:-2.75},
  {t:"ASTS",n:"AST SpaceMobile",s:"Rumfart",d:"ast-science.com",c:1.25},
  {t:"LUNR",n:"Intuitive Machines",s:"Rumfart",d:"intuitivemachines.com",c:1.55},
  {t:"RDW",n:"Redwire",s:"Rumfart",d:"redwirespace.com",c:-2.65},
  {t:"ENVX",n:"Enovix",s:"Energi-tech",d:"enovix.com",c:1.55},
  {t:"QS",n:"QuantumScape",s:"Energi-tech",d:"quantumscape.com",c:3.7},
  {t:"AMPX",n:"Amprius",s:"Energi-tech",d:"amprius.com",c:1.0},
  {t:"SLDP",n:"Solid Power",s:"Energi-tech",d:"solidpowerbattery.com",c:0.85},
  {t:"PLUG",n:"Plug Power",s:"Energi-tech",d:"plugpower.com",c:1.1},
  {t:"BE",n:"Bloom Energy",s:"Energi-tech",d:"bloomenergy.com",c:2.25},
  {t:"FSLR",n:"First Solar",s:"Energi-tech",d:"firstsolar.com",c:1.05},
  {t:"ENPH",n:"Enphase",s:"Energi-tech",d:"enphase.com",c:0.45},
  {t:"COIN",n:"Coinbase",s:"Krypto-aktier",d:"coinbase.com",c:0.35},
  {t:"MSTR",n:"MicroStrategy",s:"Krypto-aktier",d:"microstrategy.com",c:1.8},
  {t:"MARA",n:"MARA Holdings",s:"Krypto-aktier",d:"mara.com",c:-0.05},
  {t:"RIOT",n:"Riot Platforms",s:"Krypto-aktier",d:"riotplatforms.com",c:1.4},
  {t:"CLSK",n:"CleanSpark",s:"Krypto-aktier",d:"cleanspark.com",c:0.55},
  {t:"HUT",n:"Hut 8",s:"Krypto-aktier",d:"hut8.com",c:-2.45},
  {t:"BITF",n:"Bitfarms",s:"Krypto-aktier",d:"bitfarms.com",c:0.15},
  {t:"WULF",n:"TeraWulf",s:"Krypto-aktier",d:"terawulf.com",c:1.4},
  {t:"XOM",n:"ExxonMobil",s:"Energi",d:"exxonmobil.com",c:-2.3},
  {t:"CVX",n:"Chevron",s:"Energi",d:"chevron.com",c:-2.45},
  {t:"SHEL",n:"Shell",s:"Energi",d:"shell.com",c:0.5},
  {t:"BP",n:"BP",s:"Energi",d:"bp.com",c:2.8},
  {t:"COP",n:"ConocoPhillips",s:"Energi",d:"conocophillips.com",c:-3.2},
  {t:"SLB",n:"SLB",s:"Energi",d:"slb.com",c:-3.25},
  {t:"OXY",n:"Occidental",s:"Energi",d:"oxy.com",c:-1.7},
  {t:"TTE",n:"TotalEnergies",s:"Energi",d:"totalenergies.com",c:-2.65},
  {t:"JPM",n:"JPMorgan Chase",s:"Finans",d:"jpmorganchase.com",c:-2.95},
  {t:"BAC",n:"Bank of America",s:"Finans",d:"bankofamerica.com",c:5.4},
  {t:"WFC",n:"Wells Fargo",s:"Finans",d:"wellsfargo.com",c:-3.3},
  {t:"GS",n:"Goldman Sachs",s:"Finans",d:"goldmansachs.com",c:3.2},
  {t:"MS",n:"Morgan Stanley",s:"Finans",d:"morganstanley.com",c:3.5},
  {t:"C",n:"Citigroup",s:"Finans",d:"citi.com",c:-1.15},
  {t:"V",n:"Visa",s:"Finans",d:"visa.com",c:-0.2},
  {t:"MA",n:"Mastercard",s:"Finans",d:"mastercard.com",c:2.6},
  {t:"AXP",n:"American Express",s:"Finans",d:"americanexpress.com",c:-2.85},
  {t:"PYPL",n:"PayPal",s:"Finans",d:"paypal.com",c:1.75},
  {t:"HOOD",n:"Robinhood",s:"Finans",d:"robinhood.com",c:0.4},
  {t:"BLK",n:"BlackRock",s:"Finans",d:"blackrock.com",c:-3.65},
  {t:"KO",n:"Coca-Cola",s:"Forbrug",d:"coca-cola.com",c:3.2},
  {t:"PEP",n:"PepsiCo",s:"Forbrug",d:"pepsico.com",c:-3.05},
  {t:"MCD",n:"McDonald's",s:"Forbrug",d:"mcdonalds.com",c:-3.9},
  {t:"NKE",n:"Nike",s:"Forbrug",d:"nike.com",c:-3.4},
  {t:"SBUX",n:"Starbucks",s:"Forbrug",d:"starbucks.com",c:1.6},
  {t:"WMT",n:"Walmart",s:"Forbrug",d:"walmart.com",c:-2.1},
  {t:"COST",n:"Costco",s:"Forbrug",d:"costco.com",c:1.15},
  {t:"PG",n:"Procter & Gamble",s:"Forbrug",d:"pg.com",c:3.05},
  {t:"DIS",n:"Disney",s:"Forbrug",d:"disney.com",c:-3.3},
  {t:"HD",n:"Home Depot",s:"Forbrug",d:"homedepot.com",c:2.5},
  {t:"GE",n:"GE Aerospace",s:"Industri",d:"geaerospace.com",c:2.5},
  {t:"CAT",n:"Caterpillar",s:"Industri",d:"caterpillar.com",c:-3.7},
  {t:"DE",n:"Deere",s:"Industri",d:"deere.com",c:2.35},
  {t:"HON",n:"Honeywell",s:"Industri",d:"honeywell.com",c:-3.05},
  {t:"UPS",n:"UPS",s:"Industri",d:"ups.com",c:-2.1},
  {t:"MMM",n:"3M",s:"Industri",d:"3m.com",c:-2.95},
];

export const COINS = [
  {id:"bitcoin",t:"BTC",n:"Bitcoin",c:-3.65},
  {id:"ethereum",t:"ETH",n:"Ethereum",c:-3.25},
  {id:"solana",t:"SOL",n:"Solana",c:-2.6},
  {id:"binancecoin",t:"BNB",n:"BNB",c:-4.0},
  {id:"ripple",t:"XRP",n:"XRP",c:-2.0},
  {id:"cardano",t:"ADA",n:"Cardano",c:5.4},
  {id:"dogecoin",t:"DOGE",n:"Dogecoin",c:-0.15},
  {id:"avalanche-2",t:"AVAX",n:"Avalanche",c:0.7},
  {id:"chainlink",t:"LINK",n:"Chainlink",c:0.6},
  {id:"polkadot",t:"DOT",n:"Polkadot",c:-2.95},
  {id:"tron",t:"TRX",n:"TRON",c:-1.8},
  {id:"litecoin",t:"LTC",n:"Litecoin",c:-3.15},
  {id:"hyperliquid",t:"HYPE",n:"Hyperliquid",c:1.0},
  {id:"the-open-network",t:"TON",n:"Toncoin",c:-2.45},
  {id:"shiba-inu",t:"SHIB",n:"Shiba Inu",c:0.2},
  {id:"uniswap",t:"UNI",n:"Uniswap",c:-2.7},
  {id:"aptos",t:"APT",n:"Aptos",c:-3.05},
  {id:"near",t:"NEAR",n:"NEAR",c:0.2},
  {id:"stellar",t:"XLM",n:"Stellar",c:-2.45},
  {id:"cosmos",t:"ATOM",n:"Cosmos",c:0.75},
];
